version: "3.9"
services:
  finprint:
    image: finprint:latest
    build:
      context: .
      dockerfile: tools/dockerfile
      target: finprint
      args:
        - USER
        - PASSWORD
        - USER_HOME
        - INSTALL
        - PROJECT
    environment:
      - LANG
      - LC_ALL
      - LANGUAGE